[[PAPI]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "c341a966c20c1aaf5a81a0408aa79c25cfca3892"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "bca90e275cb43fab87eab09663f72216cd0c5efd57e33c4daffa3125ee157d2f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "10.2"
git-tree-sha1 = "be5e7572133ff0eb93910926ea04dc7a77b8af68"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "83bd2f1287372e71e5d87b95ad7e99e7eb5db0cf1ada463aa5b627850f08211f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.powerpc64le-linux-gnu-cuda+10.2.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "c341a966c20c1aaf5a81a0408aa79c25cfca3892"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "bca90e275cb43fab87eab09663f72216cd0c5efd57e33c4daffa3125ee157d2f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "be5e7572133ff0eb93910926ea04dc7a77b8af68"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "83bd2f1287372e71e5d87b95ad7e99e7eb5db0cf1ada463aa5b627850f08211f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "c341a966c20c1aaf5a81a0408aa79c25cfca3892"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "bca90e275cb43fab87eab09663f72216cd0c5efd57e33c4daffa3125ee157d2f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.x86_64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "f15fa1e9823f11ad5edebd89229b9167e63f509b"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "1458b17717071a1ddfdacdd110f94ce4df97296057a346e9ac63102fd753318d"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.aarch64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "55ca15031718f23b0df91c30cb3508f9b35e7f41"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "bcb783be9af7ec60cb52456d7b88fbcd4ee2ae8740c7b22a880e3b7cd5101f19"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.armv7l-linux-gnueabihf-cuda+none.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "none"
git-tree-sha1 = "be5e7572133ff0eb93910926ea04dc7a77b8af68"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "83bd2f1287372e71e5d87b95ad7e99e7eb5db0cf1ada463aa5b627850f08211f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.powerpc64le-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "038a9fd54a32c9623f1aee428e8968a6b83f7a88"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "1e5b9c484fcb2b9576dceeeebb2f59f5458b69937c20964c187b6d7f5d2d26d4"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.x86_64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "09e4b7e9baa4d79b801065659b55ee1b46f53664"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "7696bd1d62396fce8c9d69705b9ba1a19bbe8a59b343e32ecc520868f2640a04"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.aarch64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "7d44aa41073b8d5544e55e3b5c1eeaa5f280989f"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "420a30db72b1100da391a04d3507ebb4aaf5bb6ade790bb3372a4b6f9b68cfd6"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+1/PAPI.v7.0.0.armv7l-linux-musleabihf-cuda+none.tar.gz"
