[[PAPI]]
arch = "i686"
git-tree-sha1 = "f9025bc1411ff8465632ecd6cc8860f466441375"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "049026b87d4378bf29c84f0af603b419cf57846ba77ac61467877a918798002f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.i686-linux-gnu.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "8d6c0e6eca7cf957f4388898bd2f3af73b38c656"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "3ba61a1f241f5751f6dd4caf68f18e08f38696d5c0562d11b434627a6bd4112c"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "d1825087c16d9e0e5a8a12e3b6a690693b1f85fb"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "8b65ad1b8bd263730806fea39c8d480303a0b0f9f8e853531d41eefec66c2e52"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68ef5339fde2d60b57c3754f48009156b9f61441"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "a1669ac69d48f2bd006e2963a08c8aa09890099edd5f31c54ae8a201de8acea3"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.armv6l-linux-gnueabihf.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d7e632b39198227e14c197113efb30d0675540f"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "f7df1f7f314b25b63702c29fb3b58cb4f0130464e820a90737f943813477ed33"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.armv7l-linux-gnueabihf.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "none"
git-tree-sha1 = "60f2e60a00630e0d6f01d56738b6fc460e3a2d97"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "68b7ad6f26d3414da5e5069f8eaf341beedbd1a31deb21e887a67c68745995a3"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.powerpc64le-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "i686"
git-tree-sha1 = "54f1925f4ca718814e1ff2b79d43d390182087e8"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "8b2da8441ea935811898ee9a61a51ea198e24bf912addd866df90aeb8295f80b"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.i686-linux-musl.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "0f18f5913fd465355f8b736f4723e65c3d0d2500"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "646ccb771408a4ba70715b942920c008dff4c0676501f0b77658fac1fa9fdbb5"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "52b954f239169c1c0a37de3c598e8d72d2f65ed7"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "a6efb3ed1495430b329a83702c6ac4f3779029dd12ef0a18631ea383b211c0de"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "033880959b7ecb8b74f450d4db60ade15256bb90"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "63f15a5054711b113b2ea6f079af4a4af77ad7ebf2a6e8fb5b9beab121f34308"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.armv6l-linux-musleabihf.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b998d7196a05cf77176a5a9b0ad3b0ac8e002e8"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "9001b54f2d003c13560f5678d25d11fdcbacd837fc3d7b5ac0f502744b09538e"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.armv7l-linux-musleabihf.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "68ba29a4d47c76de3399a293b827add8eaf6baf6"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "fd811feca45158a9f89a7079bc266d6cd99d51567b46d80ae80095f1d3c06dd7"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.4"
cuda_platform = "sbsa"
git-tree-sha1 = "3d598a24ba7e5e7e275b5649128066ab81073a1c"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "03a6f5a18fdc8d08f58695dd285bbc6be8d6caad50d30bcfe3ba146a8735d883"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.4.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "66b0806eb9f1bc22557b21bfd49fb461b98bdf65"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "15c175b75720215e91183c8eda8e7cd9439f5937433fc14bd91fda093190f2ca"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.5"
cuda_platform = "sbsa"
git-tree-sha1 = "fe912cb1c0002db4314834e13c2a1fc41d5f6848"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "1f7317098a0f092dc06baaf26a7fde451e7d887980d4463480a59e59562dde1f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.5.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "e523006736ab588b0610e87e0f462de2b0fbf7fc"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "38dde58473e85007a7c9894a989fa7ca89438696f1349fdb3c55ef74d2f0671b"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.6"
cuda_platform = "sbsa"
git-tree-sha1 = "e2a5703c5cf499f666657a6c7f0c87fd4e4e35e0"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "b25eaf463274b570e62d44f95b1582f2e9503ce591c43760fa5e2a519e071293"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.6.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "dec80288a92eb56518177718cdc4f5b0b7035b89"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "d19adbd38fc222ec619cf8c7c03ed1317b65a3d9ee128900225a1e474365ed0d"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.7"
cuda_platform = "sbsa"
git-tree-sha1 = "db8b7f734a4165e2006accd20965cb6946877b99"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "509473d7953d3d020d45498b6b91b5bbd613dc84d68a31642e406e54d7cdd9e0"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.7.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "489b5b5621482e5e391a1f605de8f25ffbd96289"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "9ae9bb108ae2b1d06b71cbeb319938e7bb81e4810193233b1ebef66f4ae34bee"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.8"
cuda_platform = "jetson"
git-tree-sha1 = "485f1019bfa6d25fee3aadb2154c7799dff3edf1"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "3e5d6694c313b0eb46b5c141b43da08d77ca1d792ea1c491ac771bc41a832b1c"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+11.8.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "11.8"
cuda_platform = "sbsa"
git-tree-sha1 = "820f25d6510f90524350774d212360d8770f1e15"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "25c42e2ecfe99729e7f0c7f3a43306af13e783ab3816c78301410f3775cecb02"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.8.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "1b2ed765dff1a8ee95a2f32b0e4d0dcf83ba1090"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "ddf6996e2e04977f0a3c90d63b5246c98d8c614fb0614adf1b23a396eaf31d22"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "e473f15a145f3f0f35a204a3f3a44c04bdd36bdc"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "3eb9fd9dac8679e7580b1d113d8cdae7e5c6fd9106c7e658771b552005020098"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "1fd5854e6d65edcf558f436f20b789ec9bf3948b"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "56bb44fc6402e3b4bc30c10bcbe9c5aab5e3458e221d839a64ba4a6638db4aa7"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "94ddcc70c0e7c3029f56cfd5f9e096bada55b5c3"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "1b321902531025b2c8a4887bff1ac6e1fd0c15b5934a7a0860a55d081cfcefc5"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "jetson"
git-tree-sha1 = "209de89ef9803631c3265a10e78e3586e3cff022"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "55f01e9c1cb1dc888d1ecc652c95114967a8e194362779227304764a6bf4e4cd"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.1.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.1"
cuda_platform = "sbsa"
git-tree-sha1 = "dbbd41a7bd289440abe7cc9e57b81ecde769fc4a"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "c0364208602881724b1db8e52fe68fb34a915735c7654d67d67b43cd7c1b483b"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.1.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "4c9aeb0deeeb929d7c04de3760b2775b0ac763be"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "ec935ed8700cf33948f7f296e9e93f6da0c3b8e4063d741a7d92e30727e03506"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "jetson"
git-tree-sha1 = "d0b7bf80624ed62708dd4fde1bd75851534a9919"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "23f4b8dc530c9576431dbed9b19a248659aa1d7aae704bab5d5533e6c51c7bca"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.2.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.2"
cuda_platform = "sbsa"
git-tree-sha1 = "4d2ec662d9b37adb8062d28967e34e6e0e8715bb"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "eff3bd9cdf19cfae28f1158d54bbb7c2e6a1dbf2001b6ce46eba1d875d312b1b"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.2.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "245f43ce2eee4f86433fb60e2b8dd1e144059e6f"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "95153da3d6ecd609ac4f4f49d9f0b8eedaf51062caf902cd3906feef54f39709"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "12.3"
cuda_platform = "sbsa"
git-tree-sha1 = "172f16ccaa0b71fbbbbeb45f182ac9c97a89821c"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "01fb7b3bc628394f06a1de7c0dfe9cc1897cb36773ccb4c35790ada467b91ff5"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.1.0+1/PAPI.v7.1.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.3.tar.gz"
