[[PAPI]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "b74305de432731411b8e195173a3820a3afea0c9"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "294b1e493d0049994aa2aac04f35b34ee6794f071cf9d7fc520f47e98d5bf01a"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "10.2"
git-tree-sha1 = "3e8fb6eafce8f1f5fac27b8a2a1161e16eefd1a8"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "efbd7e52e8633032b6daadd8461f7005c6cfed8b836204e3c5c2bb341803138a"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.powerpc64le-linux-gnu-cuda+10.2.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "aff55234057f2a3f43abcc726ac2bfe1929522d9"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "e2f63fe16fa96998ba9b99c69ea23aaec3610ea5e73752a7d161a67308fa5f5f"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "db39344947d87616ece98c523704ecc7e9340c85"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "dfa1b11e916b7cf20d63564fc275f2d1ab8c36426521a6d02f8c840066ab10c1"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.x86_64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "ea69aa5f7f97ca197833b90ccbd7d5c75507ff5a"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "d4cd4cfc5003270847b4514a7d458500ffb696237b4ca41d7645b76b4977e363"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.aarch64-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "37830798d55528b55c6f6ee016f0c89ab3ff6a9d"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "82d486ee8fa1ba2ec6b79092a558ee9e1ea7f3de267752d86cf50620bb633e34"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.armv7l-linux-gnueabihf-cuda+none.tar.gz"
[[PAPI]]
arch = "powerpc64le"
cuda = "none"
git-tree-sha1 = "3e8fb6eafce8f1f5fac27b8a2a1161e16eefd1a8"
lazy = true
libc = "glibc"
os = "linux"

    [[PAPI.download]]
    sha256 = "efbd7e52e8633032b6daadd8461f7005c6cfed8b836204e3c5c2bb341803138a"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.powerpc64le-linux-gnu-cuda+none.tar.gz"
[[PAPI]]
arch = "x86_64"
cuda = "none"
git-tree-sha1 = "68ddc73026cb7ebd868b8941c2ad70521a1acc19"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "72c4e17261825fa50458e98c7fba586caa9db19f5bf986dd15bc6784a085c0ad"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.x86_64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "aarch64"
cuda = "none"
git-tree-sha1 = "32a8fb22d3b8937c4fbec466e8d1be804dbaea26"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "8251c339d8d4571530424e9bec343ceb5457a3d9a378df86c76478909388f1ad"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.aarch64-linux-musl-cuda+none.tar.gz"
[[PAPI]]
arch = "armv7l"
call_abi = "eabihf"
cuda = "none"
git-tree-sha1 = "617510ac48aa1ee78302a5800de988ec6328c6a5"
lazy = true
libc = "musl"
os = "linux"

    [[PAPI.download]]
    sha256 = "db367e954c05b04cd351c06bd8cca4c7d7114e9acd323cdead61f28a4afab5fb"
    url = "https://github.com/JuliaBinaryWrappers/PAPI_jll.jl/releases/download/PAPI-v7.0.0+6/PAPI.v7.0.0.armv7l-linux-musleabihf-cuda+none.tar.gz"
